### PR TITLE
Change aap-gcp to gcp within all GCP modules and assemblies

### PR DESCRIPTION
**Pull request by ariordan-redhat**
- Change every instance of `aap-gcp` in all modules and assemblies to `gcp`.
- Rename GCP assemblies and modules to eliminate `aap-`
- Update stories.adoc to use the new filenames

### CODE REVIEW

**Comment by ariordan-redhat** [comment]
For internal instances, ran the following script (`fix-gcp.sh`) from the `/stories` directory:
```
find . -name "*gcp*.adoc" > tmp.docx
#
while read line; do
  sed -r -i.bak s/aap-gcp/gcp/g $line
  echo "$line includes aap-gcp"
done < tmp.docx
#
rm tmp.docx
```

**Review by ianf77 — APPROVED** [review]
LGTM

**Comment by ariordan-redhat** [comment]
Script to rename the GCP files and assemblies:
```
find . -name "*gcp*.adoc" > tmp.docx
#
while read -r line; do
  newname=$(echo $line | sed 's/aap-gcp/gcp/g')
  mv $line $newname
done < tmp.docx
#
# Clean up temporary files
rm tmp.docx
```

**Comment by ariordan-redhat** [comment]
Redoing this PR after changes to GCP content.

**Pull request closed without merging**
