### PR TITLE
Update links to use PlatformVers attribute

### PR DESCRIPTION
**Pull request by ariordan-redhat**
Update links in the EDA, Hub, and Hardening guides to use the `PlatformVers` attribute instead of `2.4`.

### CODE REVIEW

**Review by emurtoug — APPROVED** [review]
LGTM, but holding off on merging so that all requested reviewers can take a look

**Comment by lmalivert** [comment]
LGTM @ariordan-redhat. Thank you! Holding off on merging for others to review 👍🏾

**Review by hherbly — APPROVED** [review]
LGTM

**Review by jself-sudoku — APPROVED** [review]
LGTM

**Pull request merged**
