### PR TITLE
Add Jenkins job for AAP on AWS docs

### PR DESCRIPTION
**Pull request by ariordan-redhat**
Add a script to the `/bin` directory to sync the AAP on AWS content to the production docs repo on Gitlab.

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
LGTM

**Comment by oraNod** [comment]
@ariordan-redhat Can you please change the commit message so it doesn't refer to a Jira ticket?

**Comment by ariordan-redhat** [comment]
Commit message amended

**Comment by oraNod** [comment]
thanks @ariordan-redhat

**Pull request merged**
